name: 'rust-cargo-install'
description: 'Install a Rust binary as fast as possible'
author: 'actions-rs team'
branding:
  icon: play-circle
  color: black
inputs:
  crate:
    description: Binary crate name
    required: true
  version:
    description: Specify a version to install
    required: false
    default: 'latest'
  use-tool-cache:
    description: Use tool cache to speed up installation
    required: false
    default: false
  use-cache:
    description: Store installed binary in the GitHub Actions cache (not used yet)
    required: false
    default: true

runs:
  using: 'node12'
  main: 'dist/index.js'
